app:
  appId: "17651032"
http:
  port: "8081"
  timeout: "300000"
fakestoreproxyapi:
  host: "fake-store-proxy-api.sg-s1.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
layer: "prc"
version: "v1"
context: "fakestore"
